### ISSUE TITLE
missing code?

### ISSUE THREAD

**Issue by jamesbeedy** [tengu-team/layer-nginx-api-gateway#1]
hey,

Just browsing and had a few questions  ....

1) Where are server.tmpl and upstream.tmpl rendered?
    - I feel like it should be obvious, but I'm drawing blanks looking at this here.
2) Is there a missing layer somewhere?
    - Possibly this is just a WIP, or possibly this layer is just missing a layer?

thanks

**Comment by merlijn-sebrechts** [comment]
This is a WIP, the idea is that `server.tmpl` gets provided by `interface:upstream`. @xannz knows more about this.

**Comment by xannz** [comment]
The templates are from a previous build which I forgot to remove. The idea is to use the [upstream](https://github.com/tengu-team/interface-upstream) to send whole config files to the api gateway so no template rendering is needed.

This is indeed still a WIP (same as the upstream interface) and changes to this charm or interface are likely to happen.

**Comment by jamesbeedy** [comment]
@galgalesh @xannz Awesome, thanks!
